services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sql/data:/var/opt/mssql/backup
      - ./sql/scripts:/docker-entrypoint-initdb.d
    command: /bin/bash /docker-entrypoint-initdb.d/restore.sh

  backend:
    build:
      context: ./GameForum-DotNet8/GameForum-DotNet8
      dockerfile: dockerfile
    container_name: dotnet-api
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=GameForumDB;User Id=sa;Password=YourStrong!Passw0rd;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
