# Stage 1: build
FROM node:18 as builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build --prod

# Stage 2: serve
FROM nginx:alpine
COPY --from=builder /app/dist/game-forum/browser /usr/share/nginx/html
EXPOSE 80